In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [7]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [11]:
a = np.random.random((2,3,5))

#Utilice este, pero dice de cuantas formas puedes encontrar, creo que se refiere a si lo hago con
#randint(distribucion discreto) o randn(distribucion normal)

In [12]:
print(a)

[[[0.99519513 0.52250543 0.08876708 0.94938661 0.73309374]
  [0.70540387 0.35758577 0.99593264 0.71588523 0.01837235]
  [0.33788697 0.97470554 0.91912451 0.81412007 0.85757566]]

 [[0.12903321 0.94487524 0.12281046 0.5733617  0.98500577]
  [0.7969992  0.57611746 0.23915119 0.79164091 0.99934383]
  [0.82427899 0.86767197 0.73096261 0.2304811  0.11583832]]]


In [16]:
b= np.full((5,2,3),1)

In [18]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [26]:
#a y b no son del mismo tamaño.
a.shape==b.shape


False

In [28]:
#No se pueden agregar a y b ya que no tienen el mismo shape o tamaño.

In [34]:
c = b.reshape(a.shape)
c.shape

(2, 3, 5)

In [36]:
d=a+c
print(d)
#Ahora si se pueden sumar ya que tienen el mismo tamaño o shape.

array([[[1.99519513, 1.52250543, 1.08876708, 1.94938661, 1.73309374],
        [1.70540387, 1.35758577, 1.99593264, 1.71588523, 1.01837235],
        [1.33788697, 1.97470554, 1.91912451, 1.81412007, 1.85757566]],

       [[1.12903321, 1.94487524, 1.12281046, 1.5733617 , 1.98500577],
        [1.7969992 , 1.57611746, 1.23915119, 1.79164091, 1.99934383],
        [1.82427899, 1.86767197, 1.73096261, 1.2304811 , 1.11583832]]])

In [39]:
print(a,'\n\n',d)
#ya que en d se sumaron a y c se tiene los mismos decimales mas 1 entero.

[[[0.99519513 0.52250543 0.08876708 0.94938661 0.73309374]
  [0.70540387 0.35758577 0.99593264 0.71588523 0.01837235]
  [0.33788697 0.97470554 0.91912451 0.81412007 0.85757566]]

 [[0.12903321 0.94487524 0.12281046 0.5733617  0.98500577]
  [0.7969992  0.57611746 0.23915119 0.79164091 0.99934383]
  [0.82427899 0.86767197 0.73096261 0.2304811  0.11583832]]] 

 [[[1.99519513 1.52250543 1.08876708 1.94938661 1.73309374]
  [1.70540387 1.35758577 1.99593264 1.71588523 1.01837235]
  [1.33788697 1.97470554 1.91912451 1.81412007 1.85757566]]

 [[1.12903321 1.94487524 1.12281046 1.5733617  1.98500577]
  [1.7969992  1.57611746 1.23915119 1.79164091 1.99934383]
  [1.82427899 1.86767197 1.73096261 1.2304811  1.11583832]]]


In [41]:
e=a*c
print(e)

array([[[0.99519513, 0.52250543, 0.08876708, 0.94938661, 0.73309374],
        [0.70540387, 0.35758577, 0.99593264, 0.71588523, 0.01837235],
        [0.33788697, 0.97470554, 0.91912451, 0.81412007, 0.85757566]],

       [[0.12903321, 0.94487524, 0.12281046, 0.5733617 , 0.98500577],
        [0.7969992 , 0.57611746, 0.23915119, 0.79164091, 0.99934383],
        [0.82427899, 0.86767197, 0.73096261, 0.2304811 , 0.11583832]]])

In [42]:
#Si son iguales a y e ya que todo numero multiplicado por uno es el mismo numero.

In [92]:
d_max=d.max()
d_min=d.min()
d_mean=d.mean()


In [84]:
f=np.empty((2,3,5),dtype=int)

array([[[1.99519513, 1.52250543, 1.08876708, 1.94938661, 1.73309374],
        [1.70540387, 1.35758577, 1.99593264, 1.71588523, 1.01837235],
        [1.33788697, 1.97470554, 1.91912451, 1.81412007, 1.85757566]],

       [[1.12903321, 1.94487524, 1.12281046, 1.5733617 , 1.98500577],
        [1.7969992 , 1.57611746, 1.23915119, 1.79164091, 1.99934383],
        [1.82427899, 1.86767197, 1.73096261, 1.2304811 , 1.11583832]]])

In [87]:
pri=0
seg=0
ter=0
for i in d:
    for v in i:
        for dat in v:
            if (dat > d_min) and (dat < d_mean):
                f[pri,seg,ter]=25
            elif (dat > d_mean) and (dat < d_max):
                f[pri,seg,ter]=75
            elif (dat == d_mean):
                f[pri,seg,ter]=50
            elif (dat == d_min) :
                f[pri,seg,ter]=0
            elif (dat == d_max):
                f[pri,seg,ter]=100
            
            ter+=1
        ter=0
        seg+=1
    seg=0
    pri+=1
print(d)
print(f)

[[[1.99519513 1.52250543 1.08876708 1.94938661 1.73309374]
  [1.70540387 1.35758577 1.99593264 1.71588523 1.01837235]
  [1.33788697 1.97470554 1.91912451 1.81412007 1.85757566]]

 [[1.12903321 1.94487524 1.12281046 1.5733617  1.98500577]
  [1.7969992  1.57611746 1.23915119 1.79164091 1.99934383]
  [1.82427899 1.86767197 1.73096261 1.2304811  1.11583832]]]
[[[ 75  25  25  75  75]
  [ 75  25  75  75   0]
  [ 25  75  75  75  75]]

 [[ 25  75  25  25  75]
  [ 75  25  25  75 100]
  [ 75  75  75  25  25]]]


In [91]:
f2=np.empty((2,3,5),dtype=str)
pri=0
seg=0
ter=0
for i in d:
    for v in i:
        for dat in v:
            if (dat > d_min) and (dat < d_mean):
                f2[pri,seg,ter]='B'
            elif (dat > d_mean) and (dat < d_max):
                f2[pri,seg,ter]='D'
            elif (dat == d_mean):
                f2[pri,seg,ter]='C'
            elif (dat == d_min) :
                f2[pri,seg,ter]='A'
            elif (dat == d_max):
                f2[pri,seg,ter]='E'
            
            ter+=1
        ter=0
        seg+=1
    seg=0
    pri+=1
print(f2)


[[['D' 'B' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'A']
  ['B' 'D' 'D' 'D' 'D']]

 [['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'E']
  ['D' 'D' 'D' 'B' 'B']]]
