In [6]:
import numpy as np
print("version:\n",np.__version__)
print("configuración:\n",np.show_config())

version:
 1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
configuración:
 None


In [9]:
np.full((2, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
print(a.size)
print(b.size)

NameError: name 'a' is not defined

In [12]:
b = np.full((5,2,3),1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [16]:
b.reshape(5,2,3)
c = np.transpose(b.reshape(5,2,3))
print(c.shape)

(3, 2, 5)


In [ ]:
 [[[0.31629521 0.28135139 0.7506942  0.67273096 0.64933259]
  [0.30903164 0.71504697 0.30583365 0.97991152 0.93824606]
  [0.86040907 0.01736018 0.17875997 0.4768334  0.63094783]]

 [[0.69089407 0.01017301 0.66359863 0.51217615 0.02717345]
  [0.63696856 0.25260785 0.04427757 0.85937709 0.55197887]
  [0.96220545 0.77312776 0.87969788 0.81888992 0.24379851]]]