In [1]:
#1
import numpy as np

In [2]:
#2
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'C:\\Users\\Mercantil\\anaconda3\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Mercantil/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CB

In [3]:
#3
a = np.random.random((2,3,5))

In [4]:
#4
print(a)

[[[0.62175307 0.70250791 0.94447289 0.05256955 0.9717233 ]
  [0.00547325 0.77335789 0.64606898 0.28281538 0.95806249]
  [0.1962534  0.70985146 0.95905522 0.90226583 0.78319686]]

 [[0.95393549 0.61984797 0.78338206 0.01270616 0.58869454]
  [0.10957848 0.76927911 0.86671159 0.45167796 0.49028887]
  [0.20637975 0.40546419 0.53869626 0.38734078 0.86004463]]]


In [5]:
#5
b = np.ones((5,3,2))

In [6]:
#6
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [7]:
#7
np.array_equal(a,b)

False

In [8]:
#8
#No se puede agregar ya que la estructura de los arrays son distintas. 5 cajas, 2 filas y 3 columnas vs 2 cajas 3 filas y 5 columnas


In [9]:
#9
c = np.transpose(b)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [31]:
#10 
#Funciona porque ahora si son dos arreglos con las mismas dimensiones
d = np.concatenate((a, c), axis=0)

In [32]:
#11
print(a)
print(d)

[[[0.62175307 0.70250791 0.94447289 0.05256955 0.9717233 ]
  [0.00547325 0.77335789 0.64606898 0.28281538 0.95806249]
  [0.1962534  0.70985146 0.95905522 0.90226583 0.78319686]]

 [[0.95393549 0.61984797 0.78338206 0.01270616 0.58869454]
  [0.10957848 0.76927911 0.86671159 0.45167796 0.49028887]
  [0.20637975 0.40546419 0.53869626 0.38734078 0.86004463]]]
[[[0.62175307 0.70250791 0.94447289 0.05256955 0.9717233 ]
  [0.00547325 0.77335789 0.64606898 0.28281538 0.95806249]
  [0.1962534  0.70985146 0.95905522 0.90226583 0.78319686]]

 [[0.95393549 0.61984797 0.78338206 0.01270616 0.58869454]
  [0.10957848 0.76927911 0.86671159 0.45167796 0.49028887]
  [0.20637975 0.40546419 0.53869626 0.38734078 0.86004463]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.        

In [30]:
#12
e = np.multiply(a,c)
print(e)


[[[0.62175307 0.70250791 0.94447289 0.05256955 0.9717233 ]
  [0.00547325 0.77335789 0.64606898 0.28281538 0.95806249]
  [0.1962534  0.70985146 0.95905522 0.90226583 0.78319686]]

 [[0.95393549 0.61984797 0.78338206 0.01270616 0.58869454]
  [0.10957848 0.76927911 0.86671159 0.45167796 0.49028887]
  [0.20637975 0.40546419 0.53869626 0.38734078 0.86004463]]]


In [15]:
#13 es igual porque se está multiplicando por 1


In [18]:
#14
d_max= np.max(e)
d_min = np.min(e)
d_mean = np.mean(e)
print("Valos Max: " +str(d_max)+ "  Valor Min: " + str(d_min)+ "  Valor Mean: " + str(d_mean))

Valos Max: 0.9717233039906976  Valor Min: 0.005473250247454153  Valor Mean: 0.5851151781714405


In [21]:
#15
f = np.empty([2,3,5])


In [28]:
#16

for i in range(d.shape[ 0 ]):
    for j in range(d.shape[ 1 ]):
        for k in range( d.shape[ 2 ]):
            if ((d[i,j,k]> d_min) and (d[i,j,k] < d_mean)):  
                f[i,j,k] = 25
            if ((d[i,j,k] > d_mean) and (d[i,j,k]< d_max)):
                f[i,j,k] = 75
            if (d[i,j,k] == d_mean):
                f[i,j,k] = 50
            if  (d[i,j,k] ==  d_min):
                f[i,j,k] = 0
            if (d[i,j,k]==  d_max):
                f[i,j,k] = 100


In [29]:
#17
print(d)
print(f)

[[[0.62175307 0.70250791 0.94447289 0.05256955 0.9717233 ]
  [0.00547325 0.77335789 0.64606898 0.28281538 0.95806249]
  [0.1962534  0.70985146 0.95905522 0.90226583 0.78319686]]

 [[0.95393549 0.61984797 0.78338206 0.01270616 0.58869454]
  [0.10957848 0.76927911 0.86671159 0.45167796 0.49028887]
  [0.20637975 0.40546419 0.53869626 0.38734078 0.86004463]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]]
[[[ 75.  75.  75.  25. 100.]
  [  0.  75.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  25.  25.  75.]]]


In [38]:
for i in range(d.shape[ 0 ]):
    for j in range(d.shape[ 1 ]):
        for k in range( d.shape[ 2 ]):
            if ((d[i,j,k]> d_min) and (d[i,j,k] < d_mean)):  
                f[i,j,k] = str('A')
            if ((d[i,j,k] > d_mean) and (d[i,j,k]< d_max)):
                f[i,j,k] = str('B')
            if (d[i,j,k] == d_mean):
                f[i,j,k] = str('C')
            if  (d[i,j,k] ==  d_min):
                f[i,j,k] = str('D')
            if (d[i,j,k]==  d_max):
                f[i,j,k]= str('E')
                
print(f)

SyntaxError: cannot assign to function call (<ipython-input-38-b834e7c31776>, line 5)